config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :tasks
  resources :adjs do
    get 'container_shipment', on: :member
    get 'bag_shipment', on: :member
    get 'half_shipment', on: :member
  end
  resources :dries
  resources :comments

  root "manu#manu"
end

app/models/adj.rb
class Adj < ApplicationRecord
  belongs_to :task
  belongs_to :trader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/drier.rb
class Drier < ApplicationRecord
  has_many :dries
end

app/models/dry.rb
class Dry < ApplicationRecord
  belongs_to :task
  belongs_to :drier

  validates :drier_id, presence: true
  validates :init_moist, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :dries
  has_many :adjs

  validates :req_user_name, presence: true
  validates :req_valiety, presence: true

end

app/models/trader.rb
class Trader < ApplicationRecord
  has_many :adjs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys:[:user_name]

  has_many :comments

  validates :user_name,
         # uniqueness: { case_sensitive: :false },
         length: { minimum: 4, maximum: 20 },
         format: { with: /\A[a-z0-9]+\z/, message: "は半角英数字です"}

  # :nameをユニークとして設定
  # validates_uniqueness_of :name

  # ログインに必要な項目として登録
  validates_presence_of :user_name

  # ログイン時に:nameのみでも認証出来るようににする
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["user_name = :value", { :value => user_name }]).first
    else
      where(conditions).first
    end
  end

  # 新規登録時にemailを必須としないようにfalseを返す
  def email_required?
   false
  end

  # 変更登録時にemailを必須としないようにfalseを返す
  def email_changed?
   false
  end

end

app/controllers/adjs_controller.rb
class AdjsController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = "調整"
    @adjs = Adj.all
    @dries = Dry.all
    @tasks = Task.all
  end

  def new
    @page = "調整登録"
    @adj = Adj.new
    @adj.task_id = params[:format]
    @adj.container_shipment = true
    @adj.bag_shipment = true
    @adj.half_shipment = true
  end

  def create
    @adj = Adj.new(adj_params)
    if @adj.save
      redirect_to adjs_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @page = "調整修正"
    @adj = Adj.find(params[:id])
  end

  def update
    @adj = Adj.find(params[:id])
    if @adj.update(adj_params)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def container_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(container_shipment:false)
       redirect_to adjs_path
    else
      render :edit
    end
  end

  def bag_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(bag_shipment:false)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def half_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(half_shipment:false)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def adj_params
    params.require(:adj).permit(:task_id, :trader_id, :container, :container_shipment, :bag, :bag_shipment, :half, :half_shipment, :adj_note)
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
  end
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end
  def new
    @page = "改善要求"
    @comment = Comment.new
  end
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to dries_path
    else
      flash.now[:alert] = @comment.errors.full_messages
      render :new
    end

  end
  def edit
  end
  def update
  end
  def show
  end
  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :title, :body, :end_flag)
  end

end

app/controllers/dries_controller.rb
class DriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = "乾燥"
    @dries = Dry.all
    @tasks = Task.all
  end

  def new
    @page = "乾燥登録"
    @dry = Dry.new
    @dry.task_id = params[:format]
  end

  def create
    @dry = Dry.new(dry_params)
    if @dry.save
      redirect_to dries_path
    else
      flash.now[:alert] = @dry.errors.full_messages
      render :new
    end
  end

  def show
    @page = "乾燥詳細"
    @dry = Dry.find(params[:id])
  end

  def edit
    @page = "乾燥修正"
    @dry = Dry.find(params[:id])
  end

  def update
    @dry = Dry.find(params[:id])
    if @dry.update(dry_params)
      redirect_to dries_path
    else
      flash.now[:alert] = @dry.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  private

  def dry_params
    params.require(:dry).permit(:task_id, :drier_id, :init_moist, :dry_condition1, :dry_condition2, :dry_condition3, :dry_condition4, :dry_condition5, :dry_condition6, :dry_note)
  end
end

app/controllers/manu_controller.rb
class ManuController < ApplicationController
  def manu
    @page = "メニュー"
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def menu
    @page = "メニュー"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = "受入"
    @tasks = Task.all
  end

  def new
    @page = "受入登録"
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      flash.now[:alert] = @task.errors.full_messages
      @page = "受入登録"
      render :new
    end
  end

  def show
    @page = "受入詳細"
    @task = Task.find(params[:id])
  end

  def edit
    @page = "受入編集"
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attribute(:task_act, false)
      redirect_to tasks_path
    else
      flash.now[:alert] = @task.errors.full_messages
      @page = "受入編集"
      render :edit
    end
  end

  def destroy
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :req_user_name, :req_valiety, :task_note, :task_act)
  end

end

app/helpers/adjs_helper.rb
module AdjsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dries_helper.rb
module DriesHelper
end

app/helpers/manu_helper.rb
module ManuHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/adjs/_form.html.erb
<%= form_with model: @adj, local: true, class: 'form-horizontal'  do |f|%>
  <%= render partial: 'layouts/errors', locals: { model: @adj } %>

  <%= f.hidden_field :task_id %>
  <%= f.hidden_field :container_shipment, value: @adj.container_shipment %>
  <%= f.hidden_field :bag_shipment, value: @adj.bag_shipment %>
  <%= f.hidden_field :half_shipment, value: @adj.half_shipment %>

  <div class="form-group">
    <label class="col-sm-3 control-label">依頼者：</label>
    <div class="col-sm-9">
      <%= @adj.task.req_user_name %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">品種：</label>
    <div class="col-sm-9">
      <%= @adj.task.req_valiety %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">業者：</label>
    <div class="col-sm-9">
      <%= f.collection_select :trader_id, Trader.all, :id, :name , { include_blank: "会社を選択してください" },  { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">フレコン：</label>
    <div class="col-sm-9">
      <% if @adj.container_shipment %>
        <%= f.number_field :container, class:"form-control" %>
      <% else %>
        <%= f.number_field :container, class:"form-control", disabled:true %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">紙袋：</label>
    <div class="col-sm-9">
      <% if @adj.bag_shipment %>
        <%= f.number_field :bag, class:"form-control" %>
      <% else %>
        <%= f.number_field :bag, class:"form-control", disabled:true %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">端量：</label>
    <div class="col-sm-9">
      <% if @adj.half_shipment %>
        <%= f.number_field :half, class:"form-control", :step => 0.01 %>
      <% else %>
        <%= f.number_field :half, class:"form-control", disabled:true  %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label">調整メモ</label>
    <div class="col-sm-9">
      <%= f.text_area :adj_note, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= f.submit "調整", class: "btn btn-primary" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= link_to '戻る', root_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/adjs/edit.html.erb
<%= render partial: 'form' %>

app/views/adjs/index.html.erb
<% @tasks.each do |task| %>
  <% if task.task_act %>
    <%= link_to '調整', new_adj_path(task, task.id), class: "btn btn-default" %>
    <%= task.req_user_name  %>
    <%= task.req_valiety  %>

    <table class="table table-borderd table-hover">
      <thead>
        <tr>
          <th>業者</th>
          <th width=25%>フレコン</th>
          <th width=25%>紙袋</th>
          <th width=25%>端量</th>
        </tr>
      </thead>
      <tbody>
        <% task.adjs.each do |adj| %>
          <% if adj.container_shipment || adj.bag_shipment || adj.half_shipment %>
            <tr>
              <th><%= link_to adj.trader.name, edit_adj_path(adj) %></th>
              <th><%= (adj.container_shipment && adj.container) ? (link_to adj.container, container_shipment_adj_path(adj),data:{confirm:"出荷しますか？"}) : adj.container %></th>
              <th><%= (adj.bag_shipment && adj.bag) ? (link_to adj.bag, bag_shipment_adj_path(adj),data:{confirm:"出荷しますか？"}) : adj.bag %></th>
              <th><%= (adj.half_shipment && adj.half) ? (link_to adj.half, half_shipment_adj_path(adj),data:{confirm:"出荷しますか？"}) : adj.half %></th>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/adjs/new.html.erb
<%= render partial: 'form' %>

app/views/adjs/show.html.erb
<h1>Adjs#show</h1>
<p>Find me in app/views/adjs/show.html.erb</p>

app/views/comments/_form.html.erb
<%= form_with model: @comment, local: true, class: 'form-horizontal' do |f| %>

  <%= f.hidden_field :user_id, value:current_user.id %>

  <div class="form-group">
    <%= f.label "題名", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :title, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "内容", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area  :body,     class:"form-control" %>
    </div>
  </div>

  <%= f.hidden_field :end_flag, value:false %>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= f.submit "投稿", class: "btn btn-primary" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= link_to '戻る', root_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= render partial: 'form' %>

app/views/dries/_form.html.erb
<%= form_with model: @dry, local: true, class: 'form-horizontal'  do |f|%>
  <%= render partial: 'layouts/errors', locals: { model: @dry } %>

  <%= f.hidden_field :task_id %>

  <div class="form-group">
    <%= f.label "依頼者", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= @dry.task.req_user_name %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "品種", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= @dry.task.req_valiety %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "乾燥機", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
    <% if @page == "乾燥修正" %>
      <%= f.hidden_field :drier_id %>
      <%= @dry.drier.name %>
    <% else %>
      <%= f.collection_select(:drier_id, Drier.all, :id, :name, { include_blank: "乾燥機を選択してください" }, class:"form-control") %>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "初期水分", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :init_moist, min: 14.0, max: 30, step: 0.1, class:"form-control" %>
    </div>
  </div>

  <%= f.hidden_field :dry_condition1 %>
  <%= f.hidden_field :dry_condition2 %>
  <%= f.hidden_field :dry_condition3 %>
  <%= f.hidden_field :dry_condition4 %>
  <%= f.hidden_field :dry_condition5 %>
  <%= f.hidden_field :dry_condition6 %>

  <div class="form-group">
    <%= f.label "メモ", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area :dry_note, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= f.submit "乾燥", class: "btn btn-primary" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= link_to '戻る', root_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/dries/edit.html.erb
<%= render partial: 'form' %>

app/views/dries/index.html.erb
<table class="table table-borderd table-striped">
  <thead>
    <tr>
      <th>開始</th>
      <th>氏名</th>
      <th>品種</th>
      <th>乾燥1</th>
      <th>乾燥2</th>
      <th>乾燥3</th>
      <th>乾燥4</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_act %>
        <tr>
          <% if task.dries.count < 4 %>
            <td><%= link_to '乾燥', new_dry_path(task, task.id), class: "btn btn-default", style: "text-orientation:upright;" %></td>
          <% else %>
            <td><%= link_to '乾燥', new_dry_path(task, task.id), class: "btn btn-default", disabled: true %></td>
          <% end %>
          <td><%= task.req_user_name  %></td>
          <td><%= task.req_valiety  %></td>
          <% task.dries.each do |d| %>
            <td><%= link_to d.drier.name, dry_path(d) %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="form-group">
  <div class="col-sm-3 control-label"></div>
  <div class="col-sm-9">
    <%= link_to '戻る', root_path, class: "btn btn-default" %>
  </div>
</div>

app/views/dries/new.html.erb
<%= render partial: 'form' %>

app/views/dries/show.html.erb
<div class="form-horizontal">
  <div class="form-group">
    <label class="col-xs-4 control-label">依頼者：</label>
    <div class="col-xs-8">
      <%= @dry.task.req_user_name %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-4 control-label">品種：</label>
    <div class="col-xs-8">
      <%= @dry.task.req_valiety %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-4 control-label">乾燥機：</label>
    <div class="col-xs-8">
      <%= @dry.drier.name %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-4 control-label">初期水分</label>
    <div class="col-xs-8">
      <%= @dry.init_moist %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-xs-4 control-label">乾燥メモ</label>
    <div class="col-xs-8">
      <%= @dry.dry_note %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="col-xs-4 control-label"></div>
  <div class="col-xs-8">
    <%= link_to '修正', edit_dry_path(@dry), class:"btn btn-default" %>
  </div>
</div>
<div class="form-group">
  <div class="col-xs-4 control-label"></div>
  <div class="col-xs-8">
    <%= link_to '戻る', dries_path, class:"btn btn-default" %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true, class: 'form-horizontal' do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label "依頼者", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :req_user_name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "品種", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :req_valiety,   class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "メモ", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area  :task_note,     class:"form-control" %>
    </div>
  </div>

  <%= f.hidden_field :task_act, value:true %>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= f.submit "受付", class: "btn btn-primary" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3 control-label"></div>
    <div class="col-sm-9">
      <%= link_to '戻る', root_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<%= button_to "登録", new_task_path, method: :get %>
<table class="table table-borderd table-striped">
  <thead>
    <tr>
      <th>氏名</th>
      <th>品種</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_act %>
        <tr>
          <td><%= link_to task.req_user_name, task  %></td>
          <td><%= task.req_valiety  %></td>
          <td>乾燥中</td>
          <td>調整中</td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= render partial: 'form' %>

app/views/tasks/show.html.erb
<center>
  <div>
    <label>依頼者：</label>
    <%= @task.req_user_name%>
  </div>
  <div>
    <label>品種：</label>
    <%= @task.req_valiety %>
  </div>
  <div>
    <label>メモ：</label>
    <%= @task.task_note %>
  </div>

  <div class="col-sm-12 col-md-4">
    <%= link_to "出荷", task_path,
        class: "btn btn-default btn-success btn-lg", method: :patch %>
  </div>
  <div class="col-sm-12 col-md-4">
    <%= link_to "編集", edit_task_path(@task),
        class: "btn btn-default btn-primary btn-lg" %>
  </div>
  <div class="col-sm-12 col-md-4">
    <%= link_to "戻る", root_path,
        class: "btn btn-default btn-primary btn-lg" %>
  </div>
</center>