config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :tasks
  resources :adjs do
    get 'container_shipment', on: :member
    get 'bag_shipment', on: :member
    get 'half_shipment', on: :member
  end
  resources :dries
  resources :comments

  root "manu#manu"
end

app/models/adj.rb
class Adj < ApplicationRecord
  belongs_to :task
  belongs_to :trader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/drier.rb
class Drier < ApplicationRecord
  has_many :dries
end

app/models/dry.rb
class Dry < ApplicationRecord
  belongs_to :task
  belongs_to :drier

  validates :drier_id, presence: true
  validates :init_moist, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :dries
  has_many :adjs

  validates :req_user_name, presence: true
  validates :req_valiety, presence: true

end

app/models/trader.rb
class Trader < ApplicationRecord
  has_many :adjs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys:[:user_name]

  has_many :comments

  validates :user_name,
         # uniqueness: { case_sensitive: :false },
         length: { minimum: 4, maximum: 20 },
         format: { with: /\A[a-z0-9]+\z/, message: "は半角英数字です"}

  # :nameをユニークとして設定
  # validates_uniqueness_of :name

  # ログインに必要な項目として登録
  validates_presence_of :user_name

  # ログイン時に:nameのみでも認証出来るようににする
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["user_name = :value", { :value => user_name }]).first
    else
      where(conditions).first
    end
  end

  # 新規登録時にemailを必須としないようにfalseを返す
  def email_required?
   false
  end

  # 変更登録時にemailを必須としないようにfalseを返す
  def email_changed?
   false
  end

end

app/controllers/adjs_controller.rb
class AdjsController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = "調整"
    @adjs = Adj.all
    @dries = Dry.all
    @tasks = Task.all
  end

  def new
    @page = "調整登録"
    @adj = Adj.new
    @adj.task_id = params[:format]
    @adj.container_shipment = true
    @adj.bag_shipment = true
    @adj.half_shipment = true
  end

  def create
    @adj = Adj.new(adj_params)
    if @adj.save
      redirect_to adjs_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @page = "調整修正"
    @adj = Adj.find(params[:id])
  end

  def update
    @adj = Adj.find(params[:id])
    if @adj.update(adj_params)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def container_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(container_shipment:false)
       redirect_to adjs_path
    else
      render :edit
    end
  end

  def bag_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(bag_shipment:false)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def half_shipment
    @adj = Adj.find(params[:id])
    if @adj.update(half_shipment:false)
      redirect_to adjs_path
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def adj_params
    params.require(:adj).permit(:task_id, :trader_id, :container, :container_shipment, :bag, :bag_shipment, :half, :half_shipment, :adj_note)
  end
end

app/controllers/dries_controller.rb
class DriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @page = "乾燥"
    @dries = Dry.all
    @tasks = Task.all
  end

  def new
    @page = "乾燥登録"
    @dry = Dry.new
    @dry.task_id = params[:format]
  end

  def create
    @dry = Dry.new(dry_params)
    if @dry.save
      redirect_to dries_path
    else
      flash.now[:alert] = @dry.errors.full_messages
      render :new
    end
  end

  def show
    @page = "乾燥詳細"
    @dry = Dry.find(params[:id])
  end

  def edit
    @page = "乾燥修正"
    @dry = Dry.find(params[:id])
  end

  def update
    @dry = Dry.find(params[:id])
    if @dry.update(dry_params)
      redirect_to dries_path
    else
      flash.now[:alert] = @dry.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  private

  def dry_params
    params.require(:dry).permit(:task_id, :drier_id, :init_moist, :dry_condition1, :dry_condition2, :dry_condition3, :dry_condition4, :dry_condition5, :dry_condition6, :dry_note)
  end
end

app/controllers/manu_controller.rb
class ManuController < ApplicationController
  def manu
    @page = "メニュー"
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def menu
    @page = "メニュー"
  end
end

app/helpers/adjs_helper.rb
module AdjsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dries_helper.rb
module DriesHelper
end

app/helpers/manu_helper.rb
module ManuHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admins/index.html.erb
<h1>admin</h1>

app/views/layouts/_errors.html.erb
<% if notice.present? %>
  <div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">乾燥メモ</a>
  </div> <!-- navbar-header -->

  <div class="collapse navbar-collapse" id="navbar-collapse-menu">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "改善要求", new_comment_path %></li>
        <li><%= link_to current_user.user_name+"設定変更", edit_user_registration_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_script.html.erb
<script>
  $( document ).ready(function() {
    // メッセージを10秒後にフェードアウトする
    $('.alert').fadeOut(10000);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DryAdjMemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render partial: 'layouts/script' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'layouts/header' %>
      <%= render partial: 'layouts/errors' %>
      <row>
        <div class="col-sm-8 col-sm-offset-2">
          <h2><%= @page %></h2>
          <%= yield %>
        </div>
      </row>
    </div>
  </body>
</html>